
default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"]="180"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"]="10"
ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]="<pwd-goes-here>"


platform :ios do
  desc "Description of what the lane does"
  lane :generate_ipa do
    get_certificates
    get_provisioning_profile
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "Project.xcodeproj"
    )
    build_app(scheme: "Project",
              workspace: "Project.xcworkspace",
             include_bitcode: true)
    upload_to_testflight
  end
end
