image: sonarsource/sonar-scanner-cli:latest

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
  GIT_DEPTH: "0"
cache:
  key: ${CI_JOB_NAME}
  paths:
    - .sonar/cache

stages:
  - Sonar

SonarQube:
  stage: Sonar
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true  
  when: manual
  allow_failure: true
  only:
    - development